export const theme = {
  colors: {
    background: '#020617',
    backgroundSoft: '#07111F',
    surface: '#0F172A',
    surfaceElevated: '#111C31',
    surfaceMuted: '#17233A',
    border: '#1E293B',
    borderStrong: '#334155',
    borderSubtle: '#162033',
    text: '#F8FAFC',
    textSoft: '#E2E8F0',
    textMuted: '#CBD5E1',
    textDim: '#94A3B8',
    accent: '#2563EB',
    accentStrong: '#1D4ED8',
    accentSoft: '#0B2A5F',
    success: '#10B981',
    successSoft: '#063D31',
    warning: '#F59E0B',
    warningSoft: '#3B2A09',
    danger: '#F43F5E',
    dangerSoft: '#3B0A18',
    neutral: '#64748B',
    white: '#FFFFFF',
    black: '#020617',
  },
  lightColors: {
    background: '#FFFFFF',
    surface: '#FFFFFF',
    surfaceElevated: '#F8FAFC',
    border: '#CBD5E1',
    borderSubtle: '#F1F5F9',
    text: '#0F172A',
    textSoft: '#334155',
    textMuted: '#64748B',
    textDim: '#94A3B8',
    accent: '#2563EB',
    success: '#10B981',
    warning: '#F59E0B',
    danger: '#E11D48',
  },
  spacing: {
    xxs: 4,
    xs: 6,
    sm: 10,
    md: 16,
    lg: 20,
    xl: 28,
    xxl: 36,
  },
  radius: {
    xs: 6,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    card: 16,
    button: 12,
    pill: 999,
  },
  typography: {
    screenTitle: 32,
    title: 22,
    cardTitle: 17,
    body: 15,
    small: 13,
    label: 10,
  },
  shadows: {
    card: {
      elevation: 0,
      shadowColor: '#000000',
      shadowOpacity: 0,
      shadowRadius: 0,
      shadowOffset: { width: 0, height: 0 },
    },
    sheet: {
      elevation: 12,
      shadowColor: '#000000',
      shadowOpacity: 0.35,
      shadowRadius: 24,
      shadowOffset: { width: 0, height: -8 },
    },
  },
};

export type StatusTone = 'accent' | 'success' | 'warning' | 'danger' | 'neutral';

export const statusTones: Record<StatusTone, { color: string; background: string; border: string }> = {
  accent: {
    color: theme.colors.accent,
    background: theme.colors.accentSoft,
    border: '#1D4ED880',
  },
  success: {
    color: theme.colors.success,
    background: theme.colors.successSoft,
    border: '#10B98155',
  },
  warning: {
    color: theme.colors.warning,
    background: theme.colors.warningSoft,
    border: '#F59E0B55',
  },
  danger: {
    color: theme.colors.danger,
    background: theme.colors.dangerSoft,
    border: '#F43F5E55',
  },
  neutral: {
    color: theme.colors.textDim,
    background: theme.colors.surfaceMuted,
    border: theme.colors.borderStrong,
  },
};
