from __future__ import annotations

import logging
from typing import Any

from sqlalchemy.ext.asyncio import AsyncSession

from backend.infrastructure.repositories.asset_catalog_repository import AssetCatalogRepository

logger = logging.getLogger(__name__)


def _default_logo_url(symbol: str, asset_class: str) -> str | None:
    normalized = str(symbol or "").strip().upper()
    if not normalized:
        return None
    if asset_class == "crypto":
        return f"https://assets.coincap.io/assets/icons/{normalized.lower()}@2x.png"
    return None


def _asset_defaults(
    *,
    symbol: str,
    display_name: str,
    asset_class: str,
    tradingview_symbol: str | None,
    yahoo_symbol: str | None,
    primary_provider: str,
    provider_symbol: str | None,
    exchange: str | None,
    market_region: str,
    timezone: str,
    base_currency: str | None,
    quote_currency: str | None,
    coingecko_id: str | None = None,
    coincap_id: str | None = None,
    entitlement_tier: str = "internal",
    refresh_policy: str | None = None,
    is_delayed: bool = False,
    metadata: dict[str, Any] | None = None,
) -> dict[str, Any]:
    normalized = str(symbol or "").strip().upper()
    return {
        "symbol": normalized,
        "display_name": display_name,
        "asset_class": asset_class,
        "logo_url": _default_logo_url(normalized, asset_class),
        "tradingview_symbol": tradingview_symbol,
        "coingecko_id": coingecko_id,
        "coincap_id": coincap_id,
        "yahoo_symbol": yahoo_symbol,
        "provider": primary_provider,
        "primary_provider": primary_provider,
        "fallback_provider": None,
        "provider_symbol": provider_symbol,
        "exchange": exchange,
        "market_region": market_region,
        "timezone": timezone,
        "base_currency": base_currency,
        "quote_currency": quote_currency,
        "entitlement_tier": entitlement_tier,
        "is_delayed": is_delayed,
        "refresh_policy": refresh_policy,
        "is_active": True,
        "metadata": metadata or {},
    }


DEFAULT_ASSET_CATALOG: dict[str, dict[str, Any]] = {
    "BTC": _asset_defaults(
        symbol="BTC",
        display_name="Bitcoin",
        asset_class="crypto",
        tradingview_symbol="BINANCE:BTCUSDT",
        yahoo_symbol="BTC-USD",
        primary_provider="binance",
        provider_symbol="BTCUSDT",
        exchange="BINANCE",
        market_region="global",
        timezone="UTC",
        base_currency="BTC",
        quote_currency="USDT",
        coingecko_id="bitcoin",
        coincap_id="bitcoin",
        refresh_policy="crypto_live_1m",
    ),
    "ETH": _asset_defaults(
        symbol="ETH",
        display_name="Ethereum",
        asset_class="crypto",
        tradingview_symbol="BINANCE:ETHUSDT",
        yahoo_symbol="ETH-USD",
        primary_provider="binance",
        provider_symbol="ETHUSDT",
        exchange="BINANCE",
        market_region="global",
        timezone="UTC",
        base_currency="ETH",
        quote_currency="USDT",
        coingecko_id="ethereum",
        coincap_id="ethereum",
        refresh_policy="crypto_live_1m",
    ),
    "SOL": _asset_defaults(
        symbol="SOL",
        display_name="Solana",
        asset_class="crypto",
        tradingview_symbol="BINANCE:SOLUSDT",
        yahoo_symbol="SOL-USD",
        primary_provider="binance",
        provider_symbol="SOLUSDT",
        exchange="BINANCE",
        market_region="global",
        timezone="UTC",
        base_currency="SOL",
        quote_currency="USDT",
        coingecko_id="solana",
        coincap_id="solana",
        refresh_policy="crypto_live_1m",
    ),
    "XRP": _asset_defaults(
        symbol="XRP",
        display_name="XRP",
        asset_class="crypto",
        tradingview_symbol="BINANCE:XRPUSDT",
        yahoo_symbol="XRP-USD",
        primary_provider="binance",
        provider_symbol="XRPUSDT",
        exchange="BINANCE",
        market_region="global",
        timezone="UTC",
        base_currency="XRP",
        quote_currency="USDT",
        refresh_policy="crypto_live_1m",
    ),
    "LINK": _asset_defaults(
        symbol="LINK",
        display_name="Chainlink",
        asset_class="crypto",
        tradingview_symbol="BINANCE:LINKUSDT",
        yahoo_symbol="LINK-USD",
        primary_provider="binance",
        provider_symbol="LINKUSDT",
        exchange="BINANCE",
        market_region="global",
        timezone="UTC",
        base_currency="LINK",
        quote_currency="USDT",
        refresh_policy="crypto_live_1m",
    ),
    "MSTR": _asset_defaults(
        symbol="MSTR",
        display_name="Strategy Inc.",
        asset_class="stock",
        tradingview_symbol="NASDAQ:MSTR",
        yahoo_symbol="MSTR",
        primary_provider="twelve_data",
        provider_symbol="MSTR",
        exchange="NASDAQ",
        market_region="us",
        timezone="America/New_York",
        base_currency=None,
        quote_currency="USD",
        refresh_policy="securities_live_5m",
    ),
    "COIN": _asset_defaults(
        symbol="COIN",
        display_name="Coinbase Global, Inc.",
        asset_class="stock",
        tradingview_symbol="NASDAQ:COIN",
        yahoo_symbol="COIN",
        primary_provider="twelve_data",
        provider_symbol="COIN",
        exchange="NASDAQ",
        market_region="us",
        timezone="America/New_York",
        base_currency=None,
        quote_currency="USD",
        refresh_policy="securities_live_5m",
    ),
    "MARA": _asset_defaults(
        symbol="MARA",
        display_name="MARA Holdings, Inc.",
        asset_class="stock",
        tradingview_symbol="NASDAQ:MARA",
        yahoo_symbol="MARA",
        primary_provider="twelve_data",
        provider_symbol="MARA",
        exchange="NASDAQ",
        market_region="us",
        timezone="America/New_York",
        base_currency=None,
        quote_currency="USD",
        refresh_policy="securities_live_5m",
    ),
    "RIOT": _asset_defaults(
        symbol="RIOT",
        display_name="Riot Platforms, Inc.",
        asset_class="stock",
        tradingview_symbol="NASDAQ:RIOT",
        yahoo_symbol="RIOT",
        primary_provider="twelve_data",
        provider_symbol="RIOT",
        exchange="NASDAQ",
        market_region="us",
        timezone="America/New_York",
        base_currency=None,
        quote_currency="USD",
        refresh_policy="securities_live_5m",
    ),
    "CLSK": _asset_defaults(
        symbol="CLSK",
        display_name="CleanSpark, Inc.",
        asset_class="stock",
        tradingview_symbol="NASDAQ:CLSK",
        yahoo_symbol="CLSK",
        primary_provider="twelve_data",
        provider_symbol="CLSK",
        exchange="NASDAQ",
        market_region="us",
        timezone="America/New_York",
        base_currency=None,
        quote_currency="USD",
        refresh_policy="securities_live_5m",
    ),
    "HUT": _asset_defaults(
        symbol="HUT",
        display_name="Hut 8 Corp.",
        asset_class="stock",
        tradingview_symbol="NASDAQ:HUT",
        yahoo_symbol="HUT",
        primary_provider="twelve_data",
        provider_symbol="HUT",
        exchange="NASDAQ",
        market_region="us",
        timezone="America/New_York",
        base_currency=None,
        quote_currency="USD",
        refresh_policy="securities_live_5m",
    ),
    "BTDR": _asset_defaults(
        symbol="BTDR",
        display_name="Bitdeer Technologies Group",
        asset_class="stock",
        tradingview_symbol="NASDAQ:BTDR",
        yahoo_symbol="BTDR",
        primary_provider="twelve_data",
        provider_symbol="BTDR",
        exchange="NASDAQ",
        market_region="us",
        timezone="America/New_York",
        base_currency=None,
        quote_currency="USD",
        refresh_policy="securities_live_5m",
    ),
    "WULF": _asset_defaults(
        symbol="WULF",
        display_name="TeraWulf Inc.",
        asset_class="stock",
        tradingview_symbol="NASDAQ:WULF",
        yahoo_symbol="WULF",
        primary_provider="twelve_data",
        provider_symbol="WULF",
        exchange="NASDAQ",
        market_region="us",
        timezone="America/New_York",
        base_currency=None,
        quote_currency="USD",
        refresh_policy="securities_live_5m",
    ),
    "CORZ": _asset_defaults(
        symbol="CORZ",
        display_name="Core Scientific, Inc.",
        asset_class="stock",
        tradingview_symbol="NASDAQ:CORZ",
        yahoo_symbol="CORZ",
        primary_provider="twelve_data",
        provider_symbol="CORZ",
        exchange="NASDAQ",
        market_region="us",
        timezone="America/New_York",
        base_currency=None,
        quote_currency="USD",
        refresh_policy="securities_live_5m",
    ),
    "SPY": _asset_defaults(
        symbol="SPY",
        display_name="SPDR S&P 500 ETF Trust",
        asset_class="etf",
        tradingview_symbol="AMEX:SPY",
        yahoo_symbol="SPY",
        primary_provider="twelve_data",
        provider_symbol="SPY",
        exchange="AMEX",
        market_region="us",
        timezone="America/New_York",
        base_currency=None,
        quote_currency="USD",
        refresh_policy="securities_live_5m",
    ),
    "QQQ": _asset_defaults(
        symbol="QQQ",
        display_name="Invesco QQQ Trust",
        asset_class="etf",
        tradingview_symbol="NASDAQ:QQQ",
        yahoo_symbol="QQQ",
        primary_provider="twelve_data",
        provider_symbol="QQQ",
        exchange="NASDAQ",
        market_region="us",
        timezone="America/New_York",
        base_currency=None,
        quote_currency="USD",
        refresh_policy="securities_live_5m",
    ),
    "IBIT": _asset_defaults(
        symbol="IBIT",
        display_name="iShares Bitcoin Trust ETF",
        asset_class="etf",
        tradingview_symbol="NASDAQ:IBIT",
        yahoo_symbol="IBIT",
        primary_provider="twelve_data",
        provider_symbol="IBIT",
        exchange="NASDAQ",
        market_region="us",
        timezone="America/New_York",
        base_currency=None,
        quote_currency="USD",
        refresh_policy="securities_live_5m",
    ),
    "FBTC": _asset_defaults(
        symbol="FBTC",
        display_name="Fidelity Wise Origin Bitcoin Fund",
        asset_class="etf",
        tradingview_symbol="AMEX:FBTC",
        yahoo_symbol="FBTC",
        primary_provider="twelve_data",
        provider_symbol="FBTC",
        exchange="AMEX",
        market_region="us",
        timezone="America/New_York",
        base_currency=None,
        quote_currency="USD",
        refresh_policy="securities_live_5m",
    ),
    "GLD": _asset_defaults(
        symbol="GLD",
        display_name="SPDR Gold Shares",
        asset_class="etf",
        tradingview_symbol="AMEX:GLD",
        yahoo_symbol="GLD",
        primary_provider="twelve_data",
        provider_symbol="GLD",
        exchange="AMEX",
        market_region="us",
        timezone="America/New_York",
        base_currency=None,
        quote_currency="USD",
        refresh_policy="securities_live_5m",
    ),
    "SPX": _asset_defaults(
        symbol="SPX",
        display_name="S&P 500 Index",
        asset_class="index",
        tradingview_symbol="SP:SPX",
        yahoo_symbol="^GSPC",
        primary_provider="twelve_data",
        provider_symbol="SPX",
        exchange="INDEX",
        market_region="us",
        timezone="America/New_York",
        base_currency=None,
        quote_currency="USD",
        refresh_policy="securities_live_5m",
        is_delayed=True,
    ),
    "NDX": _asset_defaults(
        symbol="NDX",
        display_name="Nasdaq-100 Index",
        asset_class="index",
        tradingview_symbol="NASDAQ:NDX",
        yahoo_symbol="^NDX",
        primary_provider="twelve_data",
        provider_symbol="NDX",
        exchange="INDEX",
        market_region="us",
        timezone="America/New_York",
        base_currency=None,
        quote_currency="USD",
        refresh_policy="securities_live_5m",
        is_delayed=True,
    ),
    "VIX": _asset_defaults(
        symbol="VIX",
        display_name="CBOE Volatility Index",
        asset_class="index",
        tradingview_symbol="CBOE:VIX",
        yahoo_symbol="^VIX",
        primary_provider="twelve_data",
        provider_symbol="VIX",
        exchange="CBOE",
        market_region="us",
        timezone="America/New_York",
        base_currency=None,
        quote_currency="USD",
        refresh_policy="securities_live_5m",
        is_delayed=True,
    ),
    "DXY": _asset_defaults(
        symbol="DXY",
        display_name="US Dollar Index",
        asset_class="index",
        tradingview_symbol="TVC:DXY",
        yahoo_symbol="DX-Y.NYB",
        primary_provider="twelve_data",
        provider_symbol="DXY",
        exchange="ICE",
        market_region="us",
        timezone="America/New_York",
        base_currency=None,
        quote_currency="USD",
        refresh_policy="securities_live_5m",
        is_delayed=True,
    ),
    "AAPL": _asset_defaults(
        symbol="AAPL",
        display_name="Apple Inc.",
        asset_class="stock",
        tradingview_symbol="NASDAQ:AAPL",
        yahoo_symbol="AAPL",
        primary_provider="twelve_data",
        provider_symbol="AAPL",
        exchange="NASDAQ",
        market_region="us",
        timezone="America/New_York",
        base_currency=None,
        quote_currency="USD",
        refresh_policy="securities_live_5m",
    ),
    "MSFT": _asset_defaults(
        symbol="MSFT",
        display_name="Microsoft Corporation",
        asset_class="stock",
        tradingview_symbol="NASDAQ:MSFT",
        yahoo_symbol="MSFT",
        primary_provider="twelve_data",
        provider_symbol="MSFT",
        exchange="NASDAQ",
        market_region="us",
        timezone="America/New_York",
        base_currency=None,
        quote_currency="USD",
        refresh_policy="securities_live_5m",
    ),
}


class AssetCatalogService:
    def __init__(self, session: AsyncSession):
        self.session = session
        self.repository = AssetCatalogRepository(session)

    async def get_assets(self, symbols: list[str]) -> dict[str, dict[str, Any]]:
        normalized = list(dict.fromkeys(str(symbol or "").strip().upper() for symbol in symbols if str(symbol or "").strip()))
        if not normalized:
            return {}

        try:
            db_rows = await self.repository.get_assets(normalized)
        except Exception as exc:
            logger.warning("Asset catalog query failed; falling back to defaults: %s", exc)
            db_rows = {}

        merged: dict[str, dict[str, Any]] = {}
        for symbol in normalized:
            default = DEFAULT_ASSET_CATALOG.get(symbol, self._fallback_asset(symbol))
            override = db_rows.get(symbol, {})
            asset_class = str(override.get("asset_class") or default.get("asset_class") or "unknown").lower()
            logo_url = override.get("logo_url") or default.get("logo_url") or _default_logo_url(symbol, asset_class)
            primary_provider = (
                override.get("primary_provider")
                or override.get("provider")
                or default.get("primary_provider")
                or default.get("provider")
                or "manual"
            )
            merged[symbol] = {
                **default,
                **override,
                "symbol": symbol,
                "asset_class": asset_class,
                "logo_url": logo_url,
                "provider": primary_provider,
                "primary_provider": primary_provider,
                "fallback_provider": override.get("fallback_provider") or default.get("fallback_provider"),
                "provider_symbol": override.get("provider_symbol") or default.get("provider_symbol"),
                "exchange": override.get("exchange") or default.get("exchange"),
                "market_region": override.get("market_region") or default.get("market_region") or "global",
                "timezone": override.get("timezone") or default.get("timezone") or "UTC",
                "base_currency": override.get("base_currency") or default.get("base_currency"),
                "quote_currency": override.get("quote_currency") or default.get("quote_currency"),
                "entitlement_tier": override.get("entitlement_tier") or default.get("entitlement_tier") or "internal",
                "is_delayed": bool(override.get("is_delayed") if override.get("is_delayed") is not None else default.get("is_delayed", False)),
                "refresh_policy": override.get("refresh_policy") or default.get("refresh_policy"),
                "is_active": bool(override.get("is_active") if override.get("is_active") is not None else default.get("is_active", True)),
                "metadata": override.get("metadata") or default.get("metadata") or {},
            }
        return merged

    async def get_asset(self, symbol: str) -> dict[str, Any]:
        assets = await self.get_assets([symbol])
        return assets.get(str(symbol or "").strip().upper(), self._fallback_asset(symbol))

    def _fallback_asset(self, symbol: str) -> dict[str, Any]:
        normalized = str(symbol or "").strip().upper()
        asset_class = "crypto" if normalized.isalpha() and len(normalized) <= 5 else "unknown"
        return {
            "symbol": normalized,
            "display_name": normalized or "Unknown asset",
            "asset_class": asset_class,
            "logo_url": _default_logo_url(normalized, asset_class),
            "tradingview_symbol": None,
            "coingecko_id": None,
            "coincap_id": None,
            "yahoo_symbol": None,
            "provider": "fallback",
            "primary_provider": "fallback",
            "fallback_provider": None,
            "provider_symbol": None,
            "exchange": None,
            "market_region": "global",
            "timezone": "UTC",
            "base_currency": normalized if asset_class == "crypto" else None,
            "quote_currency": "USDT" if asset_class == "crypto" else None,
            "entitlement_tier": "internal",
            "is_delayed": False,
            "refresh_policy": None,
            "is_active": True,
            "metadata": {},
        }
